---
apiVersion: v1
kind: Secret
type: goofysflex
metadata:
  name: "{{S3_BUCKET}}-creds"
  namespace: "{{NAMESPACE}}"
data:
  accesskey: YWRtaW4=
  secretkey: QWRtaW4xMjM0NQ==
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: "{{S3_BUCKET}}-bucket"
  labels:
    type: fuse
    bucket: "{{S3_BUCKET}}"
spec:
  storageClassName: goofys
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  flexVolume:
    driver: "goofysflex"
    secretRef:
      name: "{{S3_BUCKET}}-creds"
    options:
      # Required
      bucket: "{{S3_BUCKET}}"
      endpoint: "{{S3_ENDPOINT}}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{PVC_NAME}}"
  namespace: "{{NAMESPACE}}"
spec:
  storageClassName: goofys
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  selector:
    matchLabels:
      type: fuse
      bucket: "{{S3_BUCKET}}"
